apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-bridge-work
  namespace: git-bridge
  labels:
    app: git-bridge
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: your-storage-class
  resources:
    requests:
      storage: 10Gi
